### ISSUE TITLE
Bug - Message malformed: Unknown device 'False'

### ISSUE THREAD

**Issue by timewolf** [jumping2000/ha-templates#14]
### Blueprint name

CN FSM Elettrodomestici 2023.12.0

### Home Assistant Core Version

2023.12

### Home Assistant Installation Type

Home Assistant Core

### Description

when saving the blueprint i got Message malformed: Unknown device 'False'

### Automation YAML config

```yaml
description: ""
alias: CN FSM Elettrodomestici 2023.12.0
use_blueprint:
  path: jumping2000/cn_fsm_appliances.yaml
  input:
    power_plug: sensor.prese_forno_power
    energy_plug: sensor.prese_forno_energy
    status: input_select.oven_status
    status_sensor: sensor.oven_status
    counter_sensor: counter.cicli_cottura_forno
    helper_runtime: input_boolean.forno_runtime
    helper_total_energy: input_number.forno_runtime
    helper_maintenance_alert: input_number.forno_avviso_manutenzione
    appliance: forno
    media_player_google:
      - media_player.bagno
    delay_start: 53
    power_start: 5
    power_warm_up: 346
    power_cool_down: 83
    delay_middle: 3
    power_end: 7
    delay_finale: 10
    send_intermediate_notification: true
    use_centro_notifiche: true
```

### To Reproduce

use this yaml than save

### Expected behavior

should save the blueprint

### Actual Behaviour

cannot save

### Additional Details

- [ ] I'd like to help developing a fix for this issue.
